version: '3.8'
services:
  dev_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: mophat
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - 5434:5432
    networks:
      - mophat
networks:
  mophat:
